name: Coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
      
jobs:
  coveralls:
    name: Coveralls GitHub Action
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls GitHub Action
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        uses: coverallsapp/github-action@v2.2.3
